@url = http://localhost:8080/api/packinup/template/item
@jwt =eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6IkJlcm5pZUBydWJpYmVyLmNvbSIsInVzZXJuYW1lIjoiQmVybmllIiwidXNlcklkIjoxfQ.xi1Csl-TcE0kY40yEPwhVYvUffFLqCH4Z105I2VWq1s

# good
post {{url}} HTTP/1.1
Content-Type: application/json
Authorization: {{jwt}}

{
    "templateItemItemId": 3,
        "templateItemTemplateId": 1,
        "templateItemQuantity": 2,
        "templateItemIsChecked": false
}

### unhappy path nonpositive quantity
post {{url}} HTTP/1.1
Content-Type: application/json
Authorization: {{jwt}}

{
    "quantity": 0,
    "isChecked": false,
    "templateId": 1,
    "itemId": 1
}

### unhappy path template does no exist
post {{url}} HTTP/1.1
Content-Type: application/json
Authorization: {{jwt}}

{
    "quantity": 1,
    "isChecked": false,
    "templateId": 10,
    "itemId": 16
}

### unhappy path item does not exist
post {{url}} HTTP/1.1
Content-Type: application/json
Authorization: {{jwt}}

{
    "quantity": 1,
    "isChecked": false,
    "templateId": 1,
    "itemId": 10
}