@url = http://localhost:8080/api/packinup/template
@jwt =eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6IkJlcm5pZUBydWJpYmVyLmNvbSIsInVzZXJuYW1lIjoiQmVybmllIiwidXNlcklkIjoxfQ.ERHA_Wr5QIf13Wj3NJSf5myjPi0VdmJNzUk04tse8BA

###

get {{url}}
Content-Type: application/json
Authorization: {{jwt}}

###
# get specific template
get {{url}}/8
Content-Type: application/json
Authorization: {{jwt}}


### Successful create (201)
post {{url}}
Content-Type: application/json
Authorization: {{jwt}}

{
  "templateName": "rufflex",
    "templateDescription": "TestString",
    "templateTripTypeId": 1
    }

### put happy path
put {{url}}/8
Content-Type: application/json
Authorization: {{jwt}}

{
  "templateName": "Testaroo Edits",
    "templateDescription": "Test Edits",
    "templateTripTypeId": 1
    }