@url = http://localhost:8080/api/packinup/template/item
@jwt =eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6IkJlcm5pZUBydWJpYmVyLmNvbSIsInVzZXJuYW1lIjoiQmVybmllIiwidXNlcklkIjoxfQ.yuCa97hFa8ZW5kChWItHJxrU63aXhSX-zdQxYSZqK5Q

post {{url}} HTTP/1.1
Content-Type: application/json
Authorization: {{jwt}}

{
    "templateItemItemId": 1,
        "templateItemTemplateId": 1,
        "templateItemQuantity": 2,
        "templateItemIsChecked": false
}

### unhappy path nonpositive quantity
# TODO THIS CRASHED
post {{url}} HTTP/1.1
Content-Type: application/json
Authorization: {{jwt}}

{
    "quantity": 0,
    "isChecked": false,
    "templateId": 1,
    "itemId": 1
}

### unhappy path template does no exist
# TODO THIS CRASHED
post {{url}} HTTP/1.1
Content-Type: application/json
Authorization: {{jwt}}

{
    "quantity": 1,
    "isChecked": false,
    "templateId": 10,
    "itemId": 16
}

### unhappy path item does not exist
# TODO THIS CRASHED
post {{url}} HTTP/1.1
Content-Type: application/json
Authorization: {{jwt}}

{
    "quantity": 1,
    "isChecked": false,
    "templateId": 1,
    "itemId": 10
}