@url = http://localhost:8080/api/packinup/template
@jwt =eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6IkJlcm5pZUBydWJpYmVyLmNvbSIsInVzZXJuYW1lIjoiQmVybmllIiwidXNlcklkIjoxfQ.XmgZ2KtDWTsDVVVgE_9hf7olajjm1bfYjUwSjuNhbOc

###

get {{url}}
Content-Type: application/json
Authorization: {{jwt}}

###
# get specific template
get {{url}}/3
Content-Type: application/json
Authorization: {{jwt}}


### Successful create (201)
post {{url}}
Content-Type: application/json
Authorization: {{jwt}}

{
  "templateName": "ruffle me timbers",
    "templateDescription": "TestString",
    "templateTripTypeId": 1
    }

### put happy path
put {{url}}/6
Content-Type: application/json
Authorization: {{jwt}}

{
  "templateName": "Testaroo Edits",
    "templateDescription": "Test Edits",
    "templateTripTypeId": 1
    }

### add items to packed list

put {{url}}/1/additem
Content-Type: application/json
Authorization: {{jwt}}

{
  "templateItemTemplateId": 1,
  "templateItemItemId": 1,
  "templateItemQuantity": 1,
    "templateItemIsChecked": false
    }


### delete template

delete {{url}}/2
Content-Type: application/json
Authorization: {{jwt}}