@url = http://localhost:8080/api/packinup/weather
@jwt =eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6IkJlcm5pZUBydWJpYmVyLmNvbSIsInVzZXJuYW1lIjoiQmVybmllIiwidXNlcklkIjoxfQ.xi1Csl-TcE0kY40yEPwhVYvUffFLqCH4Z105I2VWq1s

post {{url}} HTTP/1.1
Content-Type: application/json
Authorization: {{jwt}}

{
    "query": "manchester",
    "startDate": "2025-03-27",
    "endDate": "2025-03-28"
}