@url = http://localhost:8080/api/packinup/weather
@jwt =eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6IkJlcm5pZUBydWJpYmVyLmNvbSIsInVzZXJuYW1lIjoiQmVybmllIiwidXNlcklkIjoxfQ.ERHA_Wr5QIf13Wj3NJSf5myjPi0VdmJNzUk04tse8BA

post {{url}} HTTP/1.1
Content-Type: application/json
Authorization: {{jwt}}

{
    "query": "manchester",
    "startDate": "2025-03-27",
    "endDate": "2025-03-28"
}